shop/mainapp/urls.py
from django.urls import path

from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView, AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView
)

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQTYView.as_view(), name='change_qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order')
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('api/', include('mainapp.api.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.urls import reverse
from django.utils import timezone

import sys
from PIL import Image
from io import BytesIO

User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get("with_respect_to")
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by("-id")[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Manager):

    CATEGORY_NAME_COUNT_NAME = {
        'Смартфоны': 'smartphones__count',
        'Кирпичи': 'bricks__count',
        'Строительные блоки': 'buildingblocks__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count("smartphones", "buildingblocks", "bricks")
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Имя категории")
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (900, 900)
    MAX_IMAGE_SIZE = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name="Наименование")
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name="Изображение")
    description = models.TextField(verbose_name="Описание", null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Цена")
    quantity = models.DecimalField(max_digits=9, decimal_places=0, verbose_name="Количество")
    size = models.CharField(max_length=255, verbose_name="Размер", null=True)

    def __str__(self):
        return self.title

    def get_model_name(self):
        return self.__class__.__name__.lower()

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        min_height, min_width = self.MIN_RESOLUTION
        max_height, max_width = self.MAX_RESOLUTION
        if img.width < min_width or img.height < min_height:
            raise MinResolutionErrorException("Разрешение изображения меньше минимального!")
        else:
            if img.width > img.height:
                width_new = max_width
                height_new = (max_width * img.height) // img.width
            else:
                width_new = (max_height * img.width) // img.height
                height_new = max_height
            new_img = img.convert("RGB")
            resized_new_img = new_img.resize((width_new, height_new))

            base_img_white = Image.open('media/base/white_background.png')
            base_img_white.paste(resized_new_img, (500-width_new//2, 500-height_new//2))
            resized_new_img = base_img_white

            filestream = BytesIO()
            resized_new_img.save(filestream, 'JPEG', quality=95)
            filestream.seek(0)
            name = '{}.{}'.format(*self.image.name.split('.'))
            self.image = InMemoryUploadedFile(filestream, 'ImageField', name, 'jpeg/image', sys.getsizeof(filestream), None)
        super().save(*args, **kwargs)


class Bricks(Product):
    factory = models.CharField(max_length=255, verbose_name="Завод")
    type = models.CharField(max_length=255, choices=[("facing", "Облицовочный"),
                                                     ("construction", "Строительный"),
                                                     ("warm_ceramics", "Теплая керамика")],
                            verbose_name="Тип")
    material = models.CharField(max_length=255, verbose_name="Материал")
    voidness = models.CharField(max_length=255, choices=[("full-bodied", "Полнотелый"),
                                                         ("hollow", "Пустотелый")],
                                verbose_name="Пустотность")
    surface = models.CharField(max_length=255, choices=[("smooth", "Гладкая"),
                                                        ("grainy", "Зернистая")],
                               verbose_name="Поверхность")
    colour = models.CharField(max_length=255, verbose_name="Цвет")
    chamfer = models.BooleanField(default=True, verbose_name="Фаска")
    endurance = models.CharField(max_length=255, verbose_name="Прочность")
    frost_resistance = models.CharField(max_length=255, verbose_name="Морозостойкость")
    water_absorption = models.CharField(max_length=255, verbose_name="Водопоглощение")
    weight = models.DecimalField(max_digits=9, decimal_places=3, verbose_name="Вес 1 шт, кг")
    packaging = models.CharField(max_length=255, verbose_name="Упаковка")
    warehouse = models.CharField(max_length=255, verbose_name="Склад")

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class BuildingBlocks(Product):
    factory = models.CharField(max_length=255, verbose_name="Завод")
    type = models.CharField(max_length=255, choices=[("aerated_concrete", "Газобетонный"),
                                                     ("ceramic", "Керамический"),
                                                     ("expanded_clay_concrete", "Керамзитобетонный"),
                                                     ("foundation_fbs", "Фундаментные ФБС"),
                                                     ("concrete", "Бетонный"),
                                                     ("pazogrebnevye", "Пазогребневый")],
                            verbose_name="Тип")
    material = models.CharField(max_length=255, verbose_name="Материал")
    colour = models.CharField(max_length=255, verbose_name="Цвет")
    density = models.CharField(max_length=255, verbose_name="Плотность")
    endurance = models.CharField(max_length=255, verbose_name="Прочность")
    thermal_conductivity = models.CharField(max_length=255, verbose_name="Теплопроводность")
    frost_resistance = models.CharField(max_length=255, verbose_name="Морозостойкость")
    weight = models.DecimalField(max_digits=9, decimal_places=3, verbose_name="Вес 1 шт, кг")
    packaging = models.CharField(max_length=255, verbose_name="Упаковка")
    warehouse = models.CharField(max_length=255, verbose_name="Склад")

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphones(Product):
    diagonal = models.CharField(max_length=255, verbose_name="Диагональ")
    colour = models.CharField(max_length=255, verbose_name="Цвет")
    sd = models.BooleanField(default=True, verbose_name='Наличие SD')
    sd_volume_max = models.CharField(
        max_length=255, null=True, blank=True, verbose_name='Максимальный объем встраиваемой памяти'
    )

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

    # @property
    # def sd(self):
    #     if self.sd:
    #         return 'Да'
    #     return 'Нет'


class CartProduct(models.Model):
    user = models.ForeignKey("Customer", verbose_name="Покупатель", on_delete=models.CASCADE)
    cart = models.ForeignKey("Cart", verbose_name="Корзина", on_delete=models.CASCADE, related_name="related_products")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Общая цена")

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.content_object.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey("Customer", null=True, verbose_name="Владелец", on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name="related_cart")
    total_products = models.PositiveIntegerField(default=0)

shop/mainapp/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получения заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )

shop/mainapp/views.py
from django.db import transaction
from django.shortcuts import render
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, View

from .models import Bricks, BuildingBlocks, Smartphones, Category, LatestProducts, Customer, Cart, CartProduct
from .mixins import CategoryDetailMixin, CartMixin
from .forms import OrderForm
from .utils import recalc_cart


class BaseView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        products = LatestProducts.objects.get_products_for_main_page("bricks", "buildingblocks", "smartphones")
        context = {
            'categories': categories,
            'products': products,
            'cart': self.cart
        }
        return render(request, 'base.html', context)


class ProductDetailView(CartMixin, CategoryDetailMixin, DetailView):

    CT_MODEL_MODEL_CLASS = {
        'bricks': Bricks,
        'buildingblocks': BuildingBlocks,
        'smartphones': Smartphones
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ct_model'] = self.model._meta.model_name
        context['cart'] = self.cart
        return context


class CategoryDetailView(CartMixin, CategoryDetailMixin, DetailView):

    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'category_detail.html'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cart'] = self.cart
        return context


class AddToCartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product, created = CartProduct.objects.get_or_create(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        if created:
            self.cart.products.add(cart_product)
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, 'Товар успешно добавлен!')
        return HttpResponseRedirect('/cart/')


class DeleteFromCartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        self.cart.products.remove(cart_product)
        cart_product.delete()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, 'Товар удален!')
        return HttpResponseRedirect('/cart/')


class ChangeQTYView(CartMixin, View):

    def post(self, request, *args, **kwargs):
        ct_model, product_slug = kwargs.get('ct_model'), kwargs.get('slug')
        content_type = ContentType.objects.get(model=ct_model)
        product = content_type.model_class().objects.get(slug=product_slug)
        cart_product = CartProduct.objects.get(
            user=self.cart.owner, cart=self.cart, content_type=content_type, object_id=product.id
        )
        qty = int(request.POST.get('qty'))
        cart_product.qty = qty
        cart_product.save()
        recalc_cart(self.cart)
        messages.add_message(request, messages.INFO, 'Сумма пересчитанна!')
        return HttpResponseRedirect('/cart/')


class CartView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        context = {
            'cart': self.cart,
            'categories': categories
        }
        return render(request, 'cart.html', context)


class CheckoutView(CartMixin, View):

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        form = OrderForm(request.POST or None)
        context = {
            'cart': self.cart,
            'categories': categories,
            'form': form
        }
        return render(request, 'checkout.html', context)


class MakeOrderView(CartMixin, View):

    @transaction.atomic
    def post(self, request, *args, **kwargs):
        form = OrderForm(request.POST or None)
        customer = Customer.objects.get(user=request.user)
        if form.is_valid():
            new_order = form.save(commit=False)
            new_order.customer = customer
            new_order.first_name = form.cleaned_data['first_name']
            new_order.last_name = form.cleaned_data['last_name']
            new_order.phone = form.cleaned_data['phone']
            new_order.address = form.cleaned_data['address']
            new_order.buying_type = form.cleaned_data['buying_type']
            new_order.order_date = form.cleaned_data['order_date']
            new_order.comment = form.cleaned_data['comment']
            new_order.save()
            self.cart.in_order = True
            self.cart.save()
            new_order.cart = self.cart
            new_order.save()
            customer.orders.add(new_order)
            messages.add_message(request, messages.INFO, 'Заказ оформлен')
            return HttpResponseRedirect('/')
        return HttpResponseRedirect('/checkout/')

shop/mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    (function($) {
        $('#id_sd').on('click', function(){
            if ($('#id_sd').prop('checked') == true) {
                $('#id_sd_volume_max').prop('readonly', false)
                $('#id_sd_volume_max').val('')
                $('#id_sd_volume_max').css('background', '#121212')
            }else{
                $('#id_sd_volume_max').prop('readonly', true)
                $('#id_sd_volume_max').val('')
                $('#id_sd_volume_max').css('background', '#000000')
            }
        })
    })(django.jQuery);
</script>
{% endblock %}

shop/mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	<title>Shop Homepage - Start Bootstrap Template</title>

	<!-- Bootstrap core CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<!-- Custom styles for this template -->
	<link href="css/shop-homepage.css" rel="stylesheet">

</head>

<style>
	body {
		padding-top: 56px;
	}

	.page-footer {
	  padding: 3rem;
	  background: #333;
	  color: #fff;
	  text-align: center;
	}

	.page-footer.fixed-bottom {
	  position: fixed;
	  left: 0;
	  right: 0;
	  bottom: 0;
	  z-index: 10;
	}
</style>

<body>

	<!-- Navigation -->
	<nav class="navbar navbar-expand-tg navbar-dark bg-dark fixed-top">
		<div class="container">
			<a class="navbar-brand" href="{% url 'base' %}">Магазин</a>
<!--			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">-->
<!--				<span class="navbar-toggler-icon"></span>-->
<!--			</button>-->
<!--			<div class="collapse navbar-collapse" id="navbarResponsive">-->
				<div class="navbar" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-pill badge-danger">{{ cart.products.count }}</span></a>
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<!-- Page Content -->
	<div class="container">

		<div class="row">

			<div class="col-lg-3">

				<h2 class="my-4">Каталог:</h2>
				<div class="list-group">
					{% for category in categories %}
						<a href="{{ category.url }}" class="list-group-item">{{ category.name }} ({{ category.count }})</a>
					{% endfor %}
				</div>
			</div>
			<!-- /.col-lg-3 -->

			<div class="col-lg-9">
				{% block content %}
				{% if messages %}
					{% for message in messages %}
						<div class="alert alert-success alert-dismissible fade show" role="alert">
						  <strong>{{ message }}</strong>
						  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						  </button>
						</div>
					{% endfor %}
				{% endif %}
				<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
					<ol class="carousel-indicators">
						<li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
						<li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
						<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
					</ol>
					<div class="carousel-inner" role="listbox">
						<div class="carousel-item active">
							<img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
						</div>
						<div class="carousel-item">
							<img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
						</div>
						<div class="carousel-item">
							<img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
						</div>
					</div>
					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>

				<div class="row">

					{% for product in products %}
						<div class="col-lg-4 col-md-6 mb-4">
							<div class="card h-100">
								<a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
								<div class="card-body">
									<h4 class="card-title">
										<a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
									</h4>
									<h5>{{ product.price }} руб.</h5>
									<a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
										<button class="btn btn-danger">Добавить в корзину</button>
									</a>
								</div>
							</div>
						</div>
					{% endfor %}

				</div>
				<!-- /.row -->
			{% endblock content %}
			</div>
			<!-- /.col-lg-9 -->

		</div>
		<!-- /.row -->

	</div>
	<!-- /.container -->

	<!-- Footer -->
	<footer class="page-footer">
		<div class="container">
			<p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
		</div>
		<!-- /.container -->
	</footer>

	<!-- Footer -->
	<script src="https://code.jquery.com/jquery-3.2.1.js"></script>
	<script type="text/javascript">
        if( $(document).height() <= $(window).height() ){
		  $(".page-footer").addClass("fixed-bottom");
		}
    </script>

	<!-- Bootstrap core JavaScript -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

shop/mainapp/templates/brick_specification.html
<table class="table table-sm table-striped">
    <tbody>
        <tr>
            <td>Завод</td>
            <td>{{ product.factory }}</td>
        </tr>
        <tr>
            <td>Тип</td>
            <td>{{ product.type }}</td>
        </tr>
        <tr>
            <td>Материал</td>
            <td>{{ product.material }}</td>
        </tr>
        <tr>
            <td>Пустотность</td>
            <td>{{ product.voidness }}</td>
        </tr>
        <tr>
            <td>Поверхность</td>
            <td>{{ product.surface }}</td>
        </tr>
        <tr>
            <td>Цвет</td>
            <td>{{ product.colour }}</td>
        </tr>
        <tr>
            <td>Фаска</td>
            <td>{{ product.chamfer }}</td>
        </tr>
        <tr>
            <td>Прочность</td>
            <td>{{ product.endurance }}</td>
        </tr>
        <tr>
            <td>Морозостойкость</td>
            <td>{{ product.frost_resistance }}</td>
        </tr>
        <tr>
            <td>Водопоглощение</td>
            <td>{{ product.water_absorption }}</td>
        </tr>
        <tr>
            <td>Вес 1 шт, кг</td>
            <td>{{ product.weight }}</td>
        </tr>
        <tr>
            <td>Упаковка</td>
            <td>{{ product.packaging }}</td>
        </tr>
        <tr>
            <td>Склад</td>
            <td>{{ product.warehouse }}</td>
        </tr>
    </tbody>
</table>

shop/mainapp/templates/buildingblock_specification.html
<table class="table table-sm table-striped">
    <tbody>
        <tr>
            <td>Завод</td>
            <td>{{ product.factory }}</td>
        </tr>
        <tr>
            <td>Тип</td>
            <td>{{ product.type }}</td>
        </tr>
        <tr>
            <td>Материал</td>
            <td>{{ product.material }}</td>
        </tr>
        <tr>
            <td>Цвет</td>
            <td>{{ product.colour }}</td>
        </tr>
        <tr>
            <td>Прочность</td>
            <td>{{ product.endurance }}</td>
        </tr>
        <tr>
            <td>Плотность</td>
            <td>{{ product.density }}</td>
        </tr>
        <tr>
            <td>Морозостойкость</td>
            <td>{{ product.frost_resistance }}</td>
        </tr>
        <tr>
            <td>Теплопроводность</td>
            <td>{{ product.thermal_conductivity }}</td>
        </tr>
        <tr>
            <td>Вес 1 шт, кг</td>
            <td>{{ product.weight }}</td>
        </tr>
        <tr>
            <td>Упаковка</td>
            <td>{{ product.packaging }}</td>
        </tr>
        <tr>
            <td>Склад</td>
            <td>{{ product.warehouse }}</td>
        </tr>
    </tbody>
</table>

shop/mainapp/templates/category_detail.html
{% extends 'base.html' %}

{% block content %}

<nav aria-label="breadcrumb" class="mt-3">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
    <li class="breadcrumb-item active">{{ category.name }}</li>
  </ol>
</nav>

<div class="row">

    {% for product in category_products %}
        <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
                <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
                <div class="card-body">
                    <h4 class="card-title">
                        <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                    </h4>
                    <h5>{{ product.price }} руб.</h5>
                    <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">
						<button class="btn btn-danger">Добавить в корзину</button>
					</a>
                </div>
            </div>
        </div>
    {% endfor %}

</div>

{% endblock content %}

shop/mainapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

shop/mainapp/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

shop/mainapp/templates/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>